# … earlier steps …

  - name: Install dependencies
    run: npm install

  - name: Scaffold from prompt
    run: |
      # Pass the prompt in single quotes to avoid shell misinterpretation of backticks
      node scaffold.js '${{ github.event.inputs.project_prompt }}'

  - name: Commit & Push scaffolded code
    id: push
    run: |
      git config user.name "github-actions[bot]"
      git config user.email "actions@github.com"
      git add .
      if git diff --quiet; then
        echo "::set-output name=committed::false"
      else
        git commit -m "✨ Scaffold from prompt"
        git push
        echo "::set-output name=committed::true"
      fi

  # … deploy job …
